Implemented Marker, CustomFormatter, Zoom and some props
mskec/react-native-mp-android-chart pull request #10
Opened 2016-11-06 00:09 UTC by cesardeazevedo

I did these changes and i would like to contribute it back.

2016-11-06 10:58 UTC, mskec commented
Hey, thank you for contributing. 

Can you please add example of how this improvements are used in this repo https://github.com/mskec/react-native-mp-android-chart-example ?

You can create new screen or modify existing one.

2016-11-06 18:27 UTC, cesardeazevedo commented
i'll create a pull request...

2016-11-06 20:26 UTC, cesardeazevedo commented
it's done https://github.com/mskec/react-native-mp-android-chart-example/pull/4

2016-11-06 20:27 UTC, cesardeazevedo commented
here's a print of the marker

![screen shot 2016-11-06 at 18 26 39](https://cloud.githubusercontent.com/assets/5366959/20041346/a933af0c-a44e-11e6-88b6-1e8d2fed9efc.png)

2016-11-07 22:40 UTC, mskec requested changes
First 3 commits are fine, I just have few comments mostly regarding prop validation.

I am not really sure about the marker. It's not very customisable, it's more one implementation of marker. Also it doesn't work great with candle stick chart.
Do you think it's possible to make it in a way that you pass marker classname via props (`com.github.reactNativeMPAndroidChart.charts.MyMarkerView` in this case). Then using classLoader you load that marker and set it to chart. 
That way marker implementation doesn't need to be inside this library, but in your own application.

2016-11-07 22:40 UTC, mskec commented on lib/YAxisIface.js
> +  valueFormatter: PropTypes.string,
I think we should keep `largeValue` and `percent` constants so that it's clear what are predefined formatters.

Maybe you can try something like this:

``` lang=javascript
valueFormatter: PropTypes.oneOfType([
  PropTypes.oneOf(['largeValue', 'percent']),
  PropTypes.string
]),
```

What do you think?

2016-11-07 22:40 UTC, mskec commented on lib/BarLineChartBase.js
> +    zoom: PropTypes.shape({
you are missing `axisDependency` prop

Should other values be required?

2016-11-07 22:40 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/BarLineChartBaseManager.java
> +    public void setDoubleTapToZoomEnabled(BarLineChartBase chart, ReadableMap propMap) {
Validate all props with `BridgeUtils.validate`.

Rename method to `setZoom`

2016-11-07 23:55 UTC, cesardeazevedo commented
Thank you for the feedback, I absolutely agree on these changes.

Regarding the marker, the implementation [is from MPAndroidChart examples](https://github.com/PhilJay/MPAndroidChart/blob/4ca511c4fd23f603b3f3243cf0567ac6e080cc23/MPChartExample/src/com/xxmassdeveloper/mpchartexample/custom/MyMarkerView.java), so i don't understand why "doesn't work great with candle sticks" and "It's not very customisable", I just had to add the `markerContent` id that i could be able to change the background, and you can still change the `markerFontName`, `markerFontSize` and `markerTextColor`, so it's actually very customizable, but if you talking about the [marker shape image](https://github.com/cesardeazevedo/react-native-mp-android-chart/blob/fc31cbd0661e1bd8dd2a01cdb821ece022f94de9/android/src/main/res/drawable-nodpi/marker2.png), i've to agree, it's quite limited, but it still works for the most uses cases.

About custom markers, and i think would be great to support it, and a custom className via classLoader is actually a good idea, but this implies on those who don't want (or don't know how) to touch on the native side, i still think we should support at least a basic marker implementation.

I'd to hear from you about it, so we can achieve widespread consensus, i will update my pull request soon.

2016-11-08 08:03 UTC, mskec commented
I was mostly thinking about marker shape when I said "It's not very customizable".

Actually you are right about supporting at least one marker implementation for those who do not want to touch native side.
I'd also like to support custom markers defined in third party apps and loaded via classLoader.

Would you mind if I add few commits to this PR to improve marker support?

2016-11-09 13:31 UTC, cesardeazevedo commented
I've fixed.

Any improved on the marker support would be awesome.
Thank you.

2016-11-20 22:33 UTC, mskec commented
Hey @cesardeazevedo, sorry it took me some time to start working on it. Give me few more days to enable loading custom marker via classLoader.

2016-12-04 23:01 UTC, merged