update mpAndroidChart to V3
mskec/react-native-mp-android-chart pull request #13
Opened 2017-02-18 12:29 UTC by wuxudong

update mpAndroidChart to V3

add several new features. like xValues as number, custom marker text.

2017-02-18 14:28 UTC, mskec requested changes
@wuxudong thank you for PR!
Please move example to example repo.

2017-02-19 05:26 UTC, wuxudong commented
I revert the examples. 

A PR of examples is coming soon.

2017-02-20 01:26 UTC, wuxudong commented
Is there anything more I should change?

2017-02-20 09:11 UTC, mskec commented
I need to check if there are breaking changes and test on example app.
I'm quite busy atm, but I will try to do it in the next few days.

2017-02-25 23:28 UTC, mskec requested changes
I have taken a look at what you have done and it’s mostly working fine, however there are some breaking changes that I am not sure how to proceed with.

My goal is to have as little as possible of breaking changes and to have clear migration guide for existing users.

Could you make a list of all API changes? You can write them here and I will include them in release notes.

Regarding [values in datasets](https://github.com/mskec/react-native-mp-android-chart-example/pull/5/files#diff-d4b0988aa897088a8fde2b9f3d8c80b9R30). What do you think about allowing existing way of use as array of numbers for charts where only y component is required? Here I do not mean to replace the new way, just to also allow the old way so that we do not have breaking change there.

2017-02-25 23:28 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/ChartBaseManager.java
> +                    for (int i = 0; i < legendEntries.length; i++) {
reuse for loop where colors are parsed

2017-02-25 23:28 UTC, mskec commented on README.md
> + update version to v3.0.1
rm

2017-02-25 23:28 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/LineChartManager.java
> +    Entry createEntry(ReadableArray values, int index) {
can you set this as default implementation in ChartBaseManager?

2017-02-25 23:28 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/YAxisChartBase.java
> +            axis.setAxisMaximum((float) propMap.getDouble("axisMaxValue"));
Update prop name to match new method name. `axisMaxValue` -> `axisMaximum`.
Please do that for all method changes.

Additionally we could keep old names alongs side new and add deprecation warning if old is used.

2017-02-25 23:28 UTC, mskec commented on .gitignore
> +.idea
please remove changes you made because of examples app in this repo

2017-02-25 23:28 UTC, mskec commented on lib/PieChart.js
> +          y: PropTypes.number.isRequired,
why not `value` instead of `y` for this chart? Please also change that for Radar chart

2017-02-27 03:57 UTC, wuxudong commented
change log in brief


* new feature:

update MpAndroidChart to V3
enable custom marker value 
add several config: highlightEnabled




* api change:

     * dataset renamed to dataSet

     * yValues renamed to values,  and format changed. 
      
         for example:
         
  
lineChart    

	yValues: [y1,y2,y3]   

->
 
	values:     
		[y1, y2, y3]
		[{y:y1}, {y:y2}, {y:y3}]
		[{x:x1, y:y1}, {x:x2, y:y2}, {x:x3, y:y3}]




pieChart

  	yValues: [y1,y2,y3]

-> 
	
       values:
		[y1, y2, y3]
		[{value:y1}, {value:y2}, {value:y3}]
		[{value:y1, label: label1}, {value:y2,  label: label2}, {value:y3,  label: label3}]

other chart's dataSet.values please refer to corresponding js.

    *  xValues in datasets are moved to xAxis.valueFormatter

 valueFormatter now support:

		"largeValue" / "percent"
		custom string format like "###.###.###"
		[xLabel1, XLable2, XLable3, XLable4,...]   // this is equal to former xValues.

2017-02-27 04:05 UTC, wuxudong commented
code has already changed. please take a look.

2017-02-27 07:25 UTC, wuxudong commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/LineChartManager.java
> +    Entry createEntry(ReadableArray values, int index) {
only LineChartManager and scatterChartManager share the default implementation. so I extract all createEntry to standalone DataSetUtils.

2017-03-05 14:06 UTC, wuxudong commented
can work with react-native-mp-android-chart-example which is also under review.

2017-03-05 16:13 UTC, mskec reviewed
Thank you for updating.
Please be more systematic when changing api. We shouldn't leave anything behind.
Would you mind if I added few commits to your PRs to speed up review?

2017-03-05 16:13 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/utils/DataSetUtils.java
> +/**
Please remove this

2017-03-05 16:13 UTC, mskec commented on lib/BubbleChart.js
> +          marker:PropTypes.string,
why did you add marker here? I do not see it being used when creating entries. Am I missing something?

2017-03-05 16:13 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/LineChartManager.java
> +        if (BridgeUtils.validate(config, ReadableType.String, "mode")) {
you did not change `drawCubic` to `mode` prop type in some `lib/*Chart.js` files.

2017-03-06 03:55 UTC, wuxudong commented on lib/BubbleChart.js
> +          marker:PropTypes.string,
just like lineChart, if you add marker attribute here, then the content will displayed in marker when you select the entry.

2017-03-06 03:57 UTC, wuxudong commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/LineChartManager.java
> +        if (BridgeUtils.validate(config, ReadableType.String, "mode")) {
I think only LineChart have mode property.

2017-03-06 03:59 UTC, wuxudong commented on android/src/main/java/com/github/reactNativeMPAndroidChart/utils/DataSetUtils.java
> +/**
? they are used in DataSetUtils->createPieEntry, createRadarEntry

2017-03-06 04:05 UTC, wuxudong commented on android/src/main/java/com/github/reactNativeMPAndroidChart/utils/DataSetUtils.java
> +/**
Do you mean remove the whole class?

2017-03-06 04:09 UTC, wuxudong commented on lib/BubbleChart.js
> +          marker:PropTypes.string,
every chart type can have marker property in their data entry.

2017-03-06 09:09 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/utils/DataSetUtils.java
> +/**
No I meant remove comment

2017-03-06 09:17 UTC, mskec approved these changes
this is ok, I will merge it to `v3` branch first

2017-03-06 09:17 UTC, mskec commented on android/src/main/java/com/github/reactNativeMPAndroidChart/charts/LineChartManager.java
> +        if (BridgeUtils.validate(config, ReadableType.String, "mode")) {
oh sorry, you are right

2017-03-06 22:09 UTC, merged